name: Build and Deploy
on:
  push:
    branches: [ main ]
jobs:
  publish:
    runs-on: ubuntu-latest
    name: '@qinghuani/sse-client'
    environment: npm
    steps:
      - uses: actions/checkout@master
      - name: Install and Build
        run: |
          npm install
          npm run build
      - name: 'Publish to the npm registry'
        uses: primer/publish@3.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.SSE_CLIENT }}
          NPM_AUTH_TOKEN: ${{ secrets.NPM_SSE_CLIENT }} # 跟前面步骤中的 NPM_AUTH_TOKEN 保持一致
        with:
          default_branch: main
